spring.application.name=product

# Give this service a specific port
server.port=9071

# Tell Spring to use the H2 database
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Create the database tables automatically based on our Java code
spring.jpa.hibernate.ddl-auto=update