spring.application.name=order-service

# Give this service a specific port
server.port=9081

# Tell Spring to use the H2 database
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Create the database tables automatically based on our Java code
spring.jpa.hibernate.ddl-auto=update

# Give our circuit breaker a name (we'll call it "productServiceBreaker")
# Trip the circuit if 50% of the last 10 calls fail
resilience4j.circuitbreaker.instances.productServiceBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.productServiceBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.productServiceBreaker.failure-rate-threshold=50

# How long to wait in the OPEN state before trying HALF-OPEN
resilience4j.circuitbreaker.instances.productServiceBreaker.wait-duration-in-open-state=10s